language: cpp
os:
  - linux
  - osx
env:
  - CFLAGS="-O0 -g" QMAKEFLAGS="-config debug" PATH=/opt/qt56/bin:/usr/local/opt/qt5/bin:$PATH
addons:
  apt:
    sources:
      - sourceline: 'ppa:beineri/opt-qt563-trusty'
    packages:
      - qt56base valgrind
install:
  - if [ "${TRAVIS_OS_NAME}" != "linux" ]; then
        brew install qt5;
    fi
script:
  - make -s -f Makefile.configure configure | tee .config
  - make
        CFLAGS="$CFLAGS"
        all tests/Makefile
  - cd tests && make check -k
        TESTRUNNER=`which valgrind 2>/dev/null`
