Document: iotivity
Title: Debian iotivity Manual
Author: <insert document author here>
Abstract: This manual describes what iotivity is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/iotivity/iotivity.sgml.gz

Format: postscript
Files: /usr/share/doc/iotivity/iotivity.ps.gz

Format: text
Files: /usr/share/doc/iotivity/iotivity.text.gz

Format: HTML
Index: /usr/share/doc/iotivity/html/index.html
Files: /usr/share/doc/iotivity/html/*.html
